/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ygszeafbdrhhommcjevq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnc3plYWZiZHJoaG9tbWNqZXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2MDc0MzgsImV4cCI6MjA4MzE4MzQzOH0.iFfYgxCQR1Zb9vc-srdgIguEHgX_tbMVw1V4C8yrpgY"

export const API_URL = "http://localhost:3001/make-server-e7b4487d";